name: Build, Release, and Update TUF Metadata

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build - ${{ matrix.asset_suffix }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            spec_file: mac.spec
            asset_suffix: mac-arm64
          - os: macos-13
            spec_file: mac.spec
            asset_suffix: mac-x86_64
          - os: windows-latest
            spec_file: win.spec
            asset_suffix: win-x86

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt
          
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Create root.json from secret
        env:
          TUF_ROOT_JSON: ${{ secrets.TUF_ROOT_JSON }}
        run: echo "${{ secrets.TUF_ROOT_JSON }}" > root.json

      - name: Build with PyInstaller
        run: pyinstaller --noconfirm ${{ matrix.spec_file }}

      - name: Package for macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          VERSION="${{ github.ref_name }}"
          SUFFIX="${{ matrix.asset_suffix }}"
          ASSET="Chord-to-MIDI-GENERATOR-${VERSION}-${SUFFIX}.zip"
          (cd dist && zip -r "../${ASSET}" .)
          echo "ASSET_PATH=${ASSET}" >> $GITHUB_ENV

      - name: Package for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $VERSION = "${{ github.ref_name }}"
          $SUFFIX = "${{ matrix.asset_suffix }}"
          $ASSET  = "Chord-to-MIDI-GENERATOR-$VERSION-$SUFFIX.zip"
          Compress-Archive -Path dist\* -DestinationPath $ASSET -Force
          "ASSET_PATH=$ASSET" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_suffix }}
          path: ${{ env.ASSET_PATH }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install tufup
        run: pip install tufup

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create TUF key files from secrets
        run: |
          mkdir -p keys
          echo "${{ secrets.TUF_ROOT_KEY }}" > keys/root
          echo "${{ secrets.TUF_TARGETS_KEY }}" > keys/targets
          echo "${{ secrets.TUF_SNAPSHOT_KEY }}" > keys/snapshot
          echo "${{ secrets.TUF_TIMESTAMP_KEY }}" > keys/timestamp

      - name: Prepare repository directories
        run: mkdir -p repository/metadata repository/targets keys

      - name: Create and Sign TUF metadata for all artifacts
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          TUF_TARGETS_KEY_PASSWORD: ${{ secrets.TUF_TARGETS_KEY_PASSWORD }}
          TUF_SNAPSHOT_KEY_PASSWORD: ${{ secrets.TUF_SNAPSHOT_KEY_PASSWORD }}
          TUF_TIMESTAMP_KEY_PASSWORD: ${{ secrets.TUF_TIMESTAMP_KEY_PASSWORD }}
        run: |
          set -euo pipefail
          VER=${GITHUB_REF_NAME#v}

          # targets 등록 및 서명
          TUF_KEY_PASSWORD=$TUF_TARGETS_KEY_PASSWORD tufup targets add "$VER" "artifacts/mac-arm64/Chord-to-MIDI-GENERATOR-$GITHUB_REF_NAME-mac-arm64.zip" keys
          TUF_KEY_PASSWORD=$TUF_TARGETS_KEY_PASSWORD tufup targets add "$VER" "artifacts/mac-x86_64/Chord-to-MIDI-GENERATOR-$GITHUB_REF_NAME-mac-x86_64.zip" keys
          TUF_KEY_PASSWORD=$TUF_TARGETS_KEY_PASSWORD tufup targets add "$VER" "artifacts/win-x86/Chord-to-MIDI-GENERATOR-$GITHUB_REF_NAME-win-x86.zip" keys
          TUF_KEY_PASSWORD=$TUF_TARGETS_KEY_PASSWORD tufup sign targets keys

          # 스냅샷 서명
          TUF_KEY_PASSWORD=$TUF_SNAPSHOT_KEY_PASSWORD tufup sign snapshot keys

          # 타임스탬프 서명
          TUF_KEY_PASSWORD=$TUF_TIMESTAMP_KEY_PASSWORD tufup sign timestamp keys

          # 생성물 확인
          echo '--- repository tree ---
          ls -al repository
          ls -al repository/metadata || true
          ls -al repository/targets  || true

      - name: Push metadata (and targets) to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repository    # metadata/와 targets/ 동시 게시
          publish_branch: gh-pages
          force_orphan: true

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.zip
          draft: false
          prerelease: false
